# Generated by Django 5.1.3 on 2025-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space_X_Data', '0002_crew_last_synced_launch_last_synced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='wikipedia_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
