# Generated by Django 5.2 on 2025-04-09 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('flight_number', models.IntegerField()),
                ('wikipedia_link', models.URLField(max_length=100)),
                ('details', models.TextField()),
                ('image_link', models.URLField(max_length=100)),
                ('date_first_lunch', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rockets',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('active', models.CharField(max_length=15)),
                ('boosters', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('wikipediaLink', models.URLField(max_length=100)),
                ('company', models.CharField(max_length=20)),
                ('first_flight', models.DateField()),
                ('image_link', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('agency_name', models.CharField(max_length=30)),
                ('urlimage', models.URLField(max_length=100)),
                ('wikipediaLink', models.URLField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('launches', models.ManyToManyField(to='space_data.launch')),
            ],
        ),
        migrations.AddField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_data.rockets'),
        ),
    ]
