# Generated by Django 5.2 on 2025-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='last_synced',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='last_synced',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rockets',
            name='last_synced',
            field=models.DateField(auto_now=True),
        ),
    ]
