# Generated by Django 5.1.3 on 2025-04-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('founding_year', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('flights_count', models.IntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SpaceDevData.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('mission_description', models.TextField(blank=True, null=True)),
                ('is_upcoming', models.BooleanField(default=True)),
                ('mission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rocket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SpaceDevData.agency')),
            ],
        ),
    ]
