# Generated by Django 5.1.3 on 2025-04-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceDevData', '0002_launch_video_url_launch_wikipedia_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='wikipedia_url',
            new_name='image_url',
        ),
    ]
