# Generated by Django 5.1.3 on 2025-04-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceDevData', '0003_rename_wikipedia_url_launch_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='video_url',
        ),
    ]
