# Generated by Django 5.1.3 on 2025-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceDevData', '0004_remove_launch_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
