# Generated by Django 5.1.3 on 2025-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceDevData', '0005_astronaut_wiki_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='failreason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='infographic_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='mission_orbit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='weather_concerns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='webcast_live',
            field=models.BooleanField(default=False),
        ),
    ]
