# Generated by Django 5.1.3 on 2025-04-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpaceDevData', '0001_initial'),
        ('Space_X_Data', '0003_alter_launch_details_alter_launch_wikipedia_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSpaceDevLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_SpaceDev_by_users', to='SpaceDevData.launch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_spaceDev_launches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'launch'), name='unique_user_spaceDevLaunch')],
            },
        ),
        migrations.CreateModel(
            name='SavedSpaceXLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_SpaceX_by_users', to='Space_X_Data.launch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_SpaceX_launches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'launch'), name='unique_user_spaceXLaunch')],
            },
        ),
    ]
